nelmio_api_doc:
    documentation:
        info:
            title: Inline Calculator API
            description: Simple call API
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc/$)